language: java
script: mvn clean install -Dmaven.javadoc.skip=false
jdk:
  - openjdk8

env:
  global:
    - secure: "egzJQjsVSJqP8XtkSghRb0F2dxwEDMHCtVoIvjeN2ms/pIgxWlL2zNWwhapE1IMT9ApqJehaJ9vuUDikUPuBfd/xClwK/68t8PVVYz3EkhZiJUF7H51rIdfpAH2zK8jJp8Um7io/Pk41bqMB4FOf9RynfNoM+pgZNg43kvk28eCpU3Qm40MS5i/tX0NoxjXgUZzAeP6U/oRSonxH6sgR3bPtP5L/3n86fQAhA2+cm7AWh4+BYlX1lCbPfySFPJIsN/6ihnC4CriBnFvEsTgKl3d6tTvIFnlfpbvMiNf6znBUSCmY2Ly8Rkh8RISf809UlCUrfur4NOzmg9j44I8NUv/x9Ft3nfIVjUE8p2k/caOi9iaWkZJ4DSjGIRanLx6vkwwkjdgqsbHJmQ07+ZX5emAE8fmBm1QMaqkmZgwUeDtMN4nh7yIDbxIWLsn1c3mP4Z1BMs+r4JN+dUufjxGbgnrP4nT3gbvrKJzlWDsnU5VQYTgk9mnax+A6g7Vcnw3p2jx+1ECtB3uOtMkzdY9s3crQnDekFcrQNHfxFMo13OrUYfrAWOJekTz+rePkaxuiTfWliFKas06Ah/Kwr9J6Y5Tv4PHq1C8jkAJ+91JlKLoKaGFYn3/4jU8K9XJCnfvTc0O9vwirrRDgJngOFk/Uotb/dUFf7o/FJxUnJ90O9s0="

after_success:
  - .utility/push-javadoc-to-gh-pages.sh
